# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 389)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("background-color: #363746")
        self.centralWidget.setObjectName("centralWidget")
        self.sidebar = QtWidgets.QFrame(self.centralWidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 30, 81, 361))
        self.sidebar.setStyleSheet("background-color: #3a3b4c")
        self.sidebar.setObjectName("sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sidebar)
        self.verticalLayout.setObjectName("verticalLayout")
        self.homeViewButton = QtWidgets.QPushButton(self.sidebar)
        self.homeViewButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeViewButton.sizePolicy().hasHeightForWidth())
        self.homeViewButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.homeViewButton.setFont(font)
        self.homeViewButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.homeViewButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/desktop_windows_24dp_EAC452_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeViewButton.setIcon(icon)
        self.homeViewButton.setIconSize(QtCore.QSize(40, 40))
        self.homeViewButton.setCheckable(False)
        self.homeViewButton.setObjectName("homeViewButton")
        self.verticalLayout.addWidget(self.homeViewButton)
        self.filesViewButton = QtWidgets.QPushButton(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filesViewButton.sizePolicy().hasHeightForWidth())
        self.filesViewButton.setSizePolicy(sizePolicy)
        self.filesViewButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Downloads/files_24dp_EAC452_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filesViewButton.setIcon(icon1)
        self.filesViewButton.setIconSize(QtCore.QSize(40, 40))
        self.filesViewButton.setObjectName("filesViewButton")
        self.verticalLayout.addWidget(self.filesViewButton)
        self.configViewButton = QtWidgets.QPushButton(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configViewButton.sizePolicy().hasHeightForWidth())
        self.configViewButton.setSizePolicy(sizePolicy)
        self.configViewButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Downloads/settings_24dp_EAC452_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.configViewButton.setIcon(icon2)
        self.configViewButton.setIconSize(QtCore.QSize(40, 40))
        self.configViewButton.setObjectName("configViewButton")
        self.verticalLayout.addWidget(self.configViewButton)
        self.helpViewButton = QtWidgets.QPushButton(self.sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpViewButton.sizePolicy().hasHeightForWidth())
        self.helpViewButton.setSizePolicy(sizePolicy)
        self.helpViewButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Downloads/help_24dp_EAC452_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.helpViewButton.setIcon(icon3)
        self.helpViewButton.setIconSize(QtCore.QSize(40, 40))
        self.helpViewButton.setObjectName("helpViewButton")
        self.verticalLayout.addWidget(self.helpViewButton)
        self.navbar = QtWidgets.QFrame(self.centralWidget)
        self.navbar.setGeometry(QtCore.QRect(0, 0, 551, 41))
        self.navbar.setStyleSheet("background-color: #3a3b4c")
        self.navbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.navbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.navbar.setObjectName("navbar")
        self.statusLabel = QtWidgets.QLabel(self.navbar)
        self.statusLabel.setGeometry(QtCore.QRect(510, 0, 31, 41))
        self.statusLabel.setText("")
        self.statusLabel.setPixmap(QtGui.QPixmap("../Downloads/check_circle_24dp_78A75A_FILL0_wght400_GRAD0_opsz24.svg"))
        self.statusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel.setObjectName("statusLabel")
        self.interfaceLabel = QtWidgets.QTextEdit(self.navbar)
        self.interfaceLabel.setGeometry(QtCore.QRect(450, 10, 61, 31))
        self.interfaceLabel.setStyleSheet("color: white;\n"
"border: none;")
        self.interfaceLabel.setUndoRedoEnabled(True)
        self.interfaceLabel.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.interfaceLabel.setObjectName("interfaceLabel")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralWidget)
        self.stackedWidget.setGeometry(QtCore.QRect(80, 40, 471, 331))
        self.stackedWidget.setObjectName("stackedWidget")
        self.mainPage = QtWidgets.QWidget() # hereeeeeeeeeeeeeeeeeee
        self.mainPage.setObjectName("mainPage")
        self.textEdit = QtWidgets.QTextEdit(self.mainPage)
        self.textEdit.setGeometry(QtCore.QRect(20, 20, 81, 31))
        self.textEdit.setStyleSheet("color: white;\n"
"border: none")
        self.textEdit.setObjectName("textEdit")
        self.statusLabel_2 = QtWidgets.QLabel(self.mainPage)
        self.statusLabel_2.setGeometry(QtCore.QRect(110, 20, 31, 31))
        self.statusLabel_2.setText("")
        self.statusLabel_2.setPixmap(QtGui.QPixmap("../Downloads/check_circle_24dp_78A75A_FILL0_wght400_GRAD0_opsz24.svg"))
        self.statusLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLabel_2.setObjectName("statusLabel_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.mainPage)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 60, 111, 31))
        self.textEdit_2.setStyleSheet("color: white;\n"
"border: none")
        self.textEdit_2.setObjectName("textEdit_2")
        self.interfaceLabel_2 = QtWidgets.QTextEdit(self.mainPage)
        self.interfaceLabel_2.setGeometry(QtCore.QRect(130, 60, 61, 31))
        self.interfaceLabel_2.setStyleSheet("color: white;\n"
"border: none;")
        self.interfaceLabel_2.setUndoRedoEnabled(True)
        self.interfaceLabel_2.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.interfaceLabel_2.setObjectName("interfaceLabel_2")
        self.consoleWindow = QtWidgets.QTextEdit(self.mainPage)
        self.consoleWindow.setGeometry(QtCore.QRect(10, 110, 451, 221))
        self.consoleWindow.setStyleSheet("background-color: #1e1e1e;\n"
"    color: #00ff00;\n"
"    font-family: Consolas, monospace;\n"
"    font-size: 12pt;\n"
"    border: 1px solid #444;\n"
"    padding: 8px;")
        self.consoleWindow.setObjectName("consoleWindow")
        self.stopButton = QtWidgets.QPushButton(self.mainPage)
        self.stopButton.setGeometry(QtCore.QRect(350, 40, 93, 28))
        self.stopButton.setStyleSheet("border-radius: 10px;\n"
"background-color: #4c3a40")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Downloads/cancel_24dp_8C1A10_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon4)
        self.stopButton.setObjectName("stopButton")
        self.stackedWidget.addWidget(self.mainPage)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.interfaceLabel.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.interfaceLabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">eth0</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Status:</span></p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Interface(s):</span></p></body></html>"))
        self.interfaceLabel_2.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.interfaceLabel_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">eth0</span></p></body></html>"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
