# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'single_page_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 504)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setStyleSheet("background-color: #202229")
        self.centralWidget.setObjectName("centralWidget")
        self.statusFrame = QtWidgets.QFrame(self.centralWidget)
        self.statusFrame.setGeometry(QtCore.QRect(130, 20, 151, 41))
        self.statusFrame.setStyleSheet("background-color:  #24262e;\n"
"border-radius: 8px;\n"
"padding: 6px 12px;\n"
"color: white;\n"
"font-weight: 500;\n"
"border-top: 1px solid #393a3b;\n"
"border-bottom: 1px solid black;")
        self.statusFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.statusFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.statusFrame.setObjectName("statusFrame")
        self.statusLabel = QtWidgets.QLabel(self.statusFrame)
        self.statusLabel.setGeometry(QtCore.QRect(50, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(62)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("background-color:  transparent;\n"
"border: none;\n"
"color: #2a9b80")
        self.statusLabel.setObjectName("statusLabel")
        self.statusIcon = QtWidgets.QLabel(self.statusFrame)
        self.statusIcon.setGeometry(QtCore.QRect(0, 0, 47, 41))
        self.statusIcon.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.statusIcon.setText("")
        self.statusIcon.setObjectName("statusIcon")
        self.modeFrame = QtWidgets.QFrame(self.centralWidget)
        self.modeFrame.setGeometry(QtCore.QRect(10, 20, 101, 41))
        self.modeFrame.setStyleSheet("background-color:  #24262e;\n"
"border-radius: 8px;\n"
"padding: 6px 12px;\n"
"color: white;\n"
"font-weight: 500;\n"
"border-top: 1px solid #393a3b;\n"
"border-bottom: 1px solid black;")
        self.modeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.modeFrame.setObjectName("modeFrame")
        self.modeLabel = QtWidgets.QLabel(self.modeFrame)
        self.modeLabel.setGeometry(QtCore.QRect(10, 0, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(62)
        self.modeLabel.setFont(font)
        self.modeLabel.setStyleSheet("background-color:  transparent;\n"
"border: none;\n"
"color: white")
        self.modeLabel.setObjectName("modeLabel")
        self.timeFrame = QtWidgets.QFrame(self.centralWidget)
        self.timeFrame.setGeometry(QtCore.QRect(300, 20, 91, 41))
        self.timeFrame.setStyleSheet("background-color:  #24262e;\n"
"border-radius: 8px;\n"
"padding: 6px 12px;\n"
"color: white;\n"
"font-weight: 500;\n"
"border-top: 1px solid #393a3b;\n"
"border-bottom: 1px solid black;")
        self.timeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.timeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.timeFrame.setObjectName("timeFrame")
        self.timeLabel = QtWidgets.QLabel(self.timeFrame)
        self.timeLabel.setGeometry(QtCore.QRect(30, 0, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(62)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("background-color:  transparent;\n"
"border: none;\n"
"color: white")
        self.timeLabel.setObjectName("timeLabel")
        self.timeIcon = QtWidgets.QLabel(self.timeFrame)
        self.timeIcon.setGeometry(QtCore.QRect(0, 0, 47, 41))
        self.timeIcon.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.timeIcon.setText("")
        self.timeIcon.setPixmap(QtGui.QPixmap("assets/timer.svg"))
        self.timeIcon.setObjectName("timeIcon")
        self.interfacesFrame = QtWidgets.QFrame(self.centralWidget)
        self.interfacesFrame.setGeometry(QtCore.QRect(410, 20, 161, 41))
        self.interfacesFrame.setStyleSheet("background-color:  #24262e;\n"
"border-radius: 8px;\n"
"padding: 6px 12px;\n"
"color: white;\n"
"font-weight: 500;\n"
"border-top: 1px solid #393a3b;\n"
"border-bottom: 1px solid black;")
        self.interfacesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.interfacesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.interfacesFrame.setObjectName("interfacesFrame")
        self.interfacesLabel = QtWidgets.QLabel(self.interfacesFrame)
        self.interfacesLabel.setGeometry(QtCore.QRect(40, 0, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(62)
        self.interfacesLabel.setFont(font)
        self.interfacesLabel.setStyleSheet("background-color:  transparent;\n"
"border: none;\n"
"color: white;")
        self.interfacesLabel.setObjectName("interfacesLabel")
        self.interfacesIcon = QtWidgets.QLabel(self.interfacesFrame)
        self.interfacesIcon.setGeometry(QtCore.QRect(0, 0, 47, 41))
        self.interfacesIcon.setStyleSheet("border: none;\n"
"background-color: transparent;")
        self.interfacesIcon.setText("")
        self.interfacesIcon.setPixmap(QtGui.QPixmap("assets/interfaces.svg"))
        self.interfacesIcon.setObjectName("interfacesIcon")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_4.setGeometry(QtCore.QRect(660, 20, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(62)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("""
QPushButton {
    background-color: #24262e;
    color: #2a9b80;
    border-radius: 8px;
    padding: 6px 12px;
    font-weight: 500;
    border-top: 1px solid #393a3b;
    border-bottom: 1px solid black;                                  
}
QPushButton:hover {
    background-color: #292933;
}
"""
)
        self.pushButton_4.setCursor(QtCore.Qt.PointingHandCursor)
        self.pushButton_4.setObjectName("pushButton_4")
        self.consoleWrapper = QtWidgets.QFrame(self.centralWidget)
        self.consoleWrapper.setGeometry(QtCore.QRect(10, 80, 761, 411))
        self.consoleWrapper.setStyleSheet("border-radius: 8px;\n"
"border: 1px solid #393a3b;\n"
"background-color: #24262e;")
        self.consoleWrapper.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.consoleWrapper.setFrameShadow(QtWidgets.QFrame.Raised)
        self.consoleWrapper.setObjectName("consoleWrapper")
        self.consoleTextEdit = QtWidgets.QTextEdit(self.consoleWrapper)
        self.consoleTextEdit.setGeometry(QtCore.QRect(0, 50, 891, 361))
        self.consoleTextEdit.setStyleSheet("background-color: black;\n"
"border-bottom-left-radius: 8px;\n"
"border-bottom-top-radius: 8px;\n"
"border-top-right-radius: 0px;\n"
"border-top-left-radius: 0px;\n"
"border-top: none")
        self.consoleTextEdit.setObjectName("consoleTextEdit")
        self.allButton = QtWidgets.QPushButton(self.consoleWrapper)
        self.allButton.setGeometry(QtCore.QRect(10, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.allButton.setFont(font)
        self.allButton.setStyleSheet("color: white;\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"background-color: black;\n"
"border: none;")
        self.allButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.allButton.setObjectName("allButton")
        self.threatsOnlyButton = QtWidgets.QPushButton(self.consoleWrapper)
        self.threatsOnlyButton.setGeometry(QtCore.QRect(80, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.threatsOnlyButton.setFont(font)
        self.threatsOnlyButton.setStyleSheet("color: white;\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"border: 1px solid #1b1d23;\n"
"border-top: none;")
        self.threatsOnlyButton.setCursor(QtCore.Qt.PointingHandCursor)
        self.threatsOnlyButton.setObjectName("threatsOnlyButton")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.statusLabel.setText(_translate("MainWindow", "Running"))
        self.modeLabel.setText(_translate("MainWindow", "detect"))
        self.timeLabel.setText(_translate("MainWindow", "15s"))
        self.interfacesLabel.setText(_translate("MainWindow", "2 interfaces"))
        self.pushButton_4.setText(_translate("MainWindow", "Start"))
        self.allButton.setText(_translate("MainWindow", "All"))
        self.threatsOnlyButton.setText(_translate("MainWindow", "Threats only"))
